spring:
  application:
    name: kotlin-demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/test-database
    username: name
    password: password
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always